variables:
  KUBE_CONTEXT: "gitlab.com/kashish6707-group/manifest_repo:k8s-connection"

stages:
   - lint
   - test
   - build
   - scan
   - deploy
  

lint:
  stage: lint
  image: python:3.11
  script:
    - pip install black
    - black  src/

test:
  stage: test
  image: python:3.11
  before_script:
    - pip install --upgrade pip
    - pip install -r src/requirements.txt
    - pip install pytest
  script:
    - pytest src/

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t fastapi:v1 .
    - docker tag fastapi:v1 registry.gitlab.com/kashish6707-group/deploy_code:fastapi-v1
    - echo "$CI_JOB_TOKEN" | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
    - docker push registry.gitlab.com/kashish6707-group/deploy_code:fastapi-v1

scan:
  stage: scan
  image: aquasec/trivy:latest
  script:
    - trivy image \
        --exit-code 1 \
        --severity HIGH,CRITICAL \
        --scanners vuln \
        --username gitlab-ci-token \
        --password "$CI_JOB_TOKEN" \
        $CI_REGISTRY_IMAGE:fastapi-v1

deploy:
  image:
    name: bitnami/kubectl:latest
    entrypoint: ['']
  script:
    - kubectl config get-contexts
    - kubectl config use-context "$KUBE_CONTEXT"   
    - kubectl get pods -n prod
    - kubectl apply -k manifests/dev
   
