apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fastapi-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://gitlab.com/kashish6707-group/deploy_code.git
    targetRevision: HEAD
    path: manifests/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true